name: GitHub Pages

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment
      
jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
          
      - name: Setup Node.JS
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_PERSONAL_TOKEN }}
          publish_dir: ./build
